Download button
navikt/nav-frontend-ikoner pull request #13
Opened 2018-06-29 13:13 UTC by mjansrud

2018-06-29 13:57 UTC, alexander-svendsen requested changes

2018-06-29 13:57 UTC, alexander-svendsen commented on src/redux/store-interfaces.tsx
> +export type IconType = 'inList' | 'inPanel';
En enum kanskje ?

2018-06-29 13:57 UTC, alexander-svendsen commented on src/components/misc/information-panel.tsx
> +                <Icon icon={selectedIcon} iconClickTrigger={undefined} iconType="inPanel" iconColor="black"/>
iconClickTrigger trengs ikke sende meg når du ikke gir den en verdi

2018-06-29 13:57 UTC, alexander-svendsen commented on src/components/misc/icon.tsx
> +        let iconClass = 'icon';
`const` hvis du ikke tenker å forandre verdiene

2018-07-02 07:54 UTC, alexander-svendsen commented on src/components/misc/icon.tsx
> +        let iconClass, iconContainerClass;
bedre med en funksjon som returnerer verdien på klassen :)

2018-07-02 13:06 UTC, alexander-svendsen approved these changes
Ser bra ut 👍

2018-07-02 13:14 UTC, nutgaard commented on package.json
> +    "dotenv": "^6.0.0",
Brukes denne noe sted?

2018-07-02 13:15 UTC, nutgaard commented on src/components/buttons/download-button.tsx
> +                <button type="submit" className="knapp knapp--hoved icon-download-button">Last ned ikon</button>
Man bør unngå å ha nøstede interaktive elementer. I dette tilfellet bør heller lenken styles som en knapp.

2018-07-02 14:14 UTC, mjansrud commented on src/components/buttons/download-button.tsx
> +                <button type="submit" className="knapp knapp--hoved icon-download-button">Last ned ikon</button>
Enig, fikser det i morgen @nutgaard  :)

2018-07-03 11:52 UTC, merged