New color picker
navikt/nav-frontend-ikoner pull request #40
Opened 2018-07-30 08:32 UTC by mjansrud

2018-07-30 10:37 UTC, mjansrud commented
Ser du på denne @nutgaard ?

2018-07-31 07:33 UTC, nutgaard requested changes
Småplukk, men greit å ordne i

2018-07-31 07:33 UTC, nutgaard commented on src/components/side-panel/icon-display/icon-color-picker.less
> +  @containerSize: 25px;
ubrukt variabel?

2018-07-31 07:33 UTC, nutgaard commented on src/components/side-panel/icon-display/icon-color-picker.less
> +  @containerSize: 30px;
ubrukt?

2018-07-31 07:33 UTC, nutgaard commented on src/components/sidebar/icon-color-picker-input.tsx
> +  type: ColorPickerType | undefined;
`type?: ColorPickerType;`

2018-07-31 07:33 UTC, nutgaard commented on src/components/sidebar/icon-color-picker-swatch.tsx
> +  type: ColorPickerType | undefined;
`type?: ColorPickerType;`

2018-07-31 08:42 UTC, nutgaard approved these changes

2018-07-31 08:57 UTC, merged